### PR TITLE
Minor reorganizations in YapDatabaseExtensions.swift

### PR DESCRIPTION
**Pull request by cdzombak**
**These changes are minor, opinion-based reorganizations with no functional change; thus this PR may be closed with no hard feelings if this code churn is undesirable.**
- https://github.com/danthorpe/YapDatabaseExtensions/commit/d21165b3479f4abd7ef891dc113f83de05cf6459 separates `YapDB.Index`'s `Hashable` and `CustomStringConvertible` implementations; they're not really related and it took me a moment to realize there wasn't a reason for them to be grouped together like that.
- https://github.com/danthorpe/YapDatabaseExtensions/commit/8df385e2d9f69c98480946253c03802aaf1b5699 groups free functions operating on `Persistable`s alongside the Persistable protocol definition, as so:

### CODE REVIEW

**Comment by cdzombak** [comment]
iOS and OS X tests seem to be passing locally for me.

**Comment by danthorpe** [comment]
Yeah, it's probably just my little Mac Mini...

**Comment by danthorpe** [comment]
Can you make sure that you've pulled the latest `development` into your branches? I updated the test scripts to use iOS 9.2 yesterday.

**Comment by danthorpe** [comment]
That's why the iOS tests are failing - it's timing out looking for the simulator.

**Comment by danthorpe** [comment]
But the changes look good, I don't mind the churn if overall readability increases :+1: Thanks!

**Comment by cdzombak** [comment]
I believe I've pulled in the latest `development` via https://github.com/cdzombak/YapDatabaseExtensions/commit/61564fab61f4f45c01695d98b809715e43fa4c57 .

**Comment by danthorpe** [comment]
Yeah, I think it's okay now, last one is just testing on iOS. There were some issues with Carthage on the build machines, seems to have resolved itself now.

**Comment by danthorpe** [comment]
Will leave these here for a bit in case there are any more things you spot.

**Comment by cdzombak** [comment]
> Will leave these here for a bit in case there are any more things you spot.

:+1: thanks!

**Comment by cdzombak** [comment]
> > Will leave these here for a bit in case there are any more things you spot.
> 
> :+1: thanks!

@danthorpe I probably won't have any more proposals in the very near term. Thanks for looking over my changes!

**Comment by danthorpe** [comment]
@cdzombak okay - great stuff, will merge your PRs, thanks!

**Pull request merged**
