### PR TITLE
Convert any array arguments to sequence types.

### PR DESCRIPTION
**Pull request by danthorpe**
- [x] readAtIndexes
- [x] readByKeys
- [x] atIndexes
- [x] byKeys
- [x] write (items)

### CODE REVIEW

**Comment by danthorpe** [comment]
This change means that this is possible:

``` swift
let keys = Set(arrayLiteral: "key-1", "key-2", "key-3")
let items: [Item] = connection.readByKeys(keys)
```

**Comment by aranasaurus** [comment]
Nice, I literally _just_ wrote some code where I had to create an Array from a Set to do this. Although I was needing to send a Set to `write`, as opposed to using a Set for the keys, which I see is supported with this PR.

**Comment by danthorpe** [comment]
Well, `write` has been updated too.

**Comment by danthorpe** [comment]
Although annoyingly looks like I've missed some documentation.

**Comment by aranasaurus** [comment]
it's a never-ending battle, documentation.

**Pull request merged**
