### PR TITLE
Questions around reading, updating and metadata.

### PR DESCRIPTION
**Pull request by danthorpe**
Hey Dan

Thanks for the awesome work on the extensions! Excited about moving allot of my data layer over to structs.

I have a couple of questions if you have the time?
###### Reading

I have a `User` struct, see below for its implementation, it adopts the `Persistable` protocol.

How do I best go about cleanly reading records by key? I thought something like this would do the trick but seems to complain about `ambiguous reference to member`.

``` swift
let user: User? = User.readByKey("1")
```
###### Updating

This is more of a general question as how you approach updating records in your database, do you normally pull out an existing record, create a new struct based on that and then write the new struct to the database with the existing key?
###### Metadata

I could not seem to find a way to set the default Void metadata on the user struct. This seems wrong?

``` swift
var metadata: NSNumber? {
    return .None
}
```
##### User

``` swift
import Foundation
import ValueCoding
import YapDatabaseExtensions

struct User: Equatable {

    // MARK: - Internal Properties

    let ID: Int

    let name: String

    // MARK: - Private Properties

    // MARK: - Initializers

    init(ID: Int, name: String) {
        self.ID = ID
        self.name = name
    }

    // MARK: - Internal Methods

    // MARK: - Private Methods
}

extension User: ValueCoding {

    // MARK: - ValueCoding

    typealias Coder = UserCoder
}

extension User: Persistable {

    var identifier: Identifier {
        return "\(ID)"
    }

    static var collection: String {
        return "Users"
    }

    var metadata: NSNumber? {
        return .None
    }
}

func == (lhs: User, rhs: User) -> Bool {
    return lhs.ID == rhs.ID
}
```

### CODE REVIEW

**Comment by danthorpe** [comment]
Whoops - my bad, accidentally turned the wrong issue into a pull request....

**Comment by danthorpe** [comment]
@pnicholls sorry for having to close this - accidentally turned this issue into a totally unrelated pull request.

Regarding the compilation issue - I've just reproduced it, not entirely sure why - figured this must be something introduced in Xcode 7.2 - so I'll create a new bug for it. For now, you'll have to use the "functional" style API (which I think is what most people use anyway).

**Comment by pnicholls** [comment]
not a problem @danthorpe!

Thanks again mate.

**Comment by danthorpe** [comment]
Yep, will look into fixing this tomorrow: #75.

**Pull request closed without merging**
